/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import javax.swing.JPanel;
import login.TelaCadastro;
import login.TelaProduto;
import login.TelaVendas;
import login.RealmenteSair;

/**
 *
 * @author Home
 */
public class Menu extends javax.swing.JFrame {
    TelaProduto p = null;
    TelaFornecedor f = null;
    TelaVendas v = null;
    TelaCadastro c = null;
    Menu m = null;
    RealmenteSair rs = null;
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        Sair = new javax.swing.JLabel();
        PClientes = new javax.swing.JPanel();
        IconeCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PProdutos = new javax.swing.JPanel();
        LblProdutos = new javax.swing.JLabel();
        IconeProduto = new javax.swing.JLabel();
        PVendas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IconeVenda = new javax.swing.JLabel();
        PFornecedor = new javax.swing.JPanel();
        IconeFornecedor = new javax.swing.JLabel();
        LblFornecedor = new javax.swing.JLabel();
        FundoE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1260, 540));

        fundo.setBackground(new java.awt.Color(255, 255, 255));
        fundo.setMinimumSize(new java.awt.Dimension(1000, 540));
        fundo.setPreferredSize(new java.awt.Dimension(1000, 540));
        fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        fundo.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 30, 30));

        PClientes.setBackground(new java.awt.Color(168, 224, 99));
        PClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PClientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PClientesMousePressed(evt);
            }
        });
        PClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        IconeCliente.setForeground(new java.awt.Color(255, 255, 255));
        IconeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconeCliente.setText("Clientes");
        PClientes.add(IconeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        PClientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 160, 70));

        fundo.add(PClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        PProdutos.setBackground(new java.awt.Color(168, 224, 99));
        PProdutos.setPreferredSize(new java.awt.Dimension(200, 250));
        PProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PProdutosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PProdutosMousePressed(evt);
            }
        });
        PProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblProdutos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblProdutos.setForeground(new java.awt.Color(255, 255, 255));
        LblProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblProdutos.setText("Produtos");
        PProdutos.add(LblProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        IconeProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconeProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrinho de mercado.png"))); // NOI18N
        PProdutos.add(IconeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 4, 160, 70));

        fundo.add(PProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 160, 110));

        PVendas.setBackground(new java.awt.Color(168, 224, 99));
        PVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PVendasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PVendasMousePressed(evt);
            }
        });
        PVendas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carteira.png"))); // NOI18N
        PVendas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 160, 70));

        IconeVenda.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        IconeVenda.setForeground(new java.awt.Color(255, 255, 255));
        IconeVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconeVenda.setText("Vendas");
        PVendas.add(IconeVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        fundo.add(PVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        PFornecedor.setBackground(new java.awt.Color(168, 224, 99));
        PFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PFornecedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PFornecedorMousePressed(evt);
            }
        });
        PFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconeFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconeFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventory.png"))); // NOI18N
        PFornecedor.add(IconeFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 5, 160, 70));

        LblFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LblFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        LblFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFornecedor.setText("Fornecedor");
        PFornecedor.add(LblFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 160, -1));

        fundo.add(PFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, 110));

        FundoE.setBackground(new java.awt.Color(168, 224, 99));
        FundoE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicine.png"))); // NOI18N
        jLabel1.setText("  Droman");
        FundoE.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Drogaria & Manipulação!");
        FundoE.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        fundo.add(FundoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PClientesMouseClicked
        if (c == null){
        c = new TelaCadastro();
        }
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_PClientesMouseClicked

    private void PProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PProdutosMouseClicked
        if (p == null){
        p = new TelaProduto();
        }
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_PProdutosMouseClicked

    private void PVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PVendasMouseClicked
        if (v == null){
        v = new TelaVendas();
        }
        v.setVisible(true);
        dispose();      
    }//GEN-LAST:event_PVendasMouseClicked

    private void PClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PClientesMousePressed
        setColor(PClientes);
        resetColor(PProdutos);
        resetColor(PVendas);
        resetColor(PFornecedor);
    }//GEN-LAST:event_PClientesMousePressed

    private void PProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PProdutosMousePressed
        setColor(PProdutos);
        resetColor(PClientes);
        resetColor(PVendas);
        resetColor(PFornecedor);
    }//GEN-LAST:event_PProdutosMousePressed

    private void PVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PVendasMousePressed
        setColor(PVendas);
        resetColor(PClientes);
        resetColor(PProdutos);
        resetColor(PFornecedor);
    }//GEN-LAST:event_PVendasMousePressed

    private void PFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PFornecedorMouseClicked
        if (f == null){
        f = new TelaFornecedor();
        }
        f.setVisible(true);
        dispose();       
    }//GEN-LAST:event_PFornecedorMouseClicked

    private void PFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PFornecedorMousePressed
        setColor(PFornecedor);
        resetColor(PClientes);
        resetColor(PProdutos);
        resetColor(PVendas);
    }//GEN-LAST:event_PFornecedorMousePressed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        if (rs == null){
        rs = new RealmenteSair();
        }
        rs.setVisible(true);
    }//GEN-LAST:event_SairMouseClicked
    void setColor(JPanel panel){
	panel.setBackground(new Color(76,41,211));
    }
    void resetColor(JPanel panel){
	panel.setBackground(new Color(168,224,99));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FundoE;
    private javax.swing.JLabel IconeCliente;
    private javax.swing.JLabel IconeFornecedor;
    private javax.swing.JLabel IconeProduto;
    private javax.swing.JLabel IconeVenda;
    private javax.swing.JLabel LblFornecedor;
    private javax.swing.JLabel LblProdutos;
    private javax.swing.JPanel PClientes;
    private javax.swing.JPanel PFornecedor;
    private javax.swing.JPanel PProdutos;
    private javax.swing.JPanel PVendas;
    private javax.swing.JLabel Sair;
    private javax.swing.JPanel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
