/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Home
 */
public class TelaVendas extends javax.swing.JFrame {

    /**
     * Creates new form ListaDeProdutos
     */
    public TelaVendas() {
        initComponents();
        precoTotal.setEditable(false);
        data.setEditable(false);
        
        data.setText(getDate());
        this.setLocationRelativeTo(null);
        
           ArrayList<ProdutosC> produtos = new ProdutosC().executaSelectProdutos("Select * from produtos");
           
           DefaultListModel<ProdutosC> model = new DefaultListModel<>();
           for(int c =0;c<produtos.size();c++) {
               model.addElement(produtos.get(c));
              
           }
           ListaProdutos.setModel(model);
           
       
  
           ArrayList<CadastroS> clientes = new CadastroS().listaClientes();
        
        for(CadastroS c : clientes){
            Clientes.addItem(c);
        }
        
        
        }
    
    
    private String getDate() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        return dateFormat.format(date);
    }
    
    
    private int contaQtd(ProdutosC p){
        int qtd = 0;
        ListModel<ProdutosC> modelAtual = ListaSelecionado.getModel();
        for(int c = 0; c<modelAtual.getSize(); c++) {
            if(modelAtual.getElementAt(c).equals(p)){
                qtd++;
            }
        }
        
        return qtd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Clientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSelecionado = new javax.swing.JList<>();
        Remover = new javax.swing.JButton();
        Adicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProdutos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Finalizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        data = new javax.swing.JTextField();
        precoTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(855, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 11, -1, -1));

        Clientes.setBackground(new java.awt.Color(233, 234, 239));
        Clientes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Clientes.setForeground(new java.awt.Color(153, 153, 153));
        Clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome" }));
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ListaSelecionado.setBackground(new java.awt.Color(233, 234, 239));
        ListaSelecionado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ListaSelecionado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaSelecionadoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaSelecionado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 540, 150));

        Remover.setBackground(new java.awt.Color(255, 51, 51));
        Remover.setFont(new java.awt.Font("Leelawadee", 1, 11)); // NOI18N
        Remover.setForeground(new java.awt.Color(255, 255, 255));
        Remover.setText("Remover");
        Remover.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoverMouseClicked(evt);
            }
        });
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });
        jPanel1.add(Remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 90, 30));

        Adicionar.setBackground(new java.awt.Color(168, 224, 99));
        Adicionar.setFont(new java.awt.Font("Leelawadee", 1, 11)); // NOI18N
        Adicionar.setForeground(new java.awt.Color(255, 255, 255));
        Adicionar.setText("Adicionar");
        Adicionar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdicionarMouseClicked(evt);
            }
        });
        Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(Adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 90, 30));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ListaProdutos.setBackground(new java.awt.Color(233, 234, 239));
        ListaProdutos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ListaProdutos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(ListaProdutos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 540, 150));

        jPanel2.setBackground(new java.awt.Color(52, 174, 95));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados de vendas");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 600, -1));

        Finalizar.setBackground(new java.awt.Color(255, 165, 0));
        Finalizar.setFont(new java.awt.Font("Leelawadee", 1, 11)); // NOI18N
        Finalizar.setForeground(new java.awt.Color(255, 255, 255));
        Finalizar.setText("Finalizar");
        Finalizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 90, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 540, 2));
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 60, 70, -1));
        jPanel1.add(precoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 510, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        ProdutosC p = ListaSelecionado.getSelectedValue();   
        
        ListModel<ProdutosC> modelAtual = ListaSelecionado.getModel();
        DefaultListModel<ProdutosC> model = new DefaultListModel<>();
        
        for(int c = 0; c<modelAtual.getSize(); c++) {
            model.addElement(modelAtual.getElementAt(c));
        }
        
        model.removeElement(p);
        ListaSelecionado.setModel(model);
        
        calculaTotal();
                               
    }//GEN-LAST:event_RemoverActionPerformed

    private void ListaSelecionadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaSelecionadoValueChanged

    }//GEN-LAST:event_ListaSelecionadoValueChanged

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        
       cadastraVenda();
       JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
        
        
    }//GEN-LAST:event_FinalizarActionPerformed

    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarActionPerformed
    ProdutosC p = ListaProdutos.getSelectedValue();
        ListModel<ProdutosC> modelAtual = ListaSelecionado.getModel();
        
        if(p.quantidade-contaQtd(p) <= 0){
            JOptionPane.showMessageDialog(null, "Produto sem estoque");
        }else{
            DefaultListModel<ProdutosC> model = new DefaultListModel<>();
            for(int c = 0; c<modelAtual.getSize(); c++) {
                model.addElement(modelAtual.getElementAt(c));
            }

            model.addElement(p);
            ListaSelecionado.setModel(model);

            calculaTotal();
        }
        
    }//GEN-LAST:event_AdicionarActionPerformed

    private void AdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdicionarMouseClicked
                       
    }//GEN-LAST:event_AdicionarMouseClicked

    private void RemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoverMouseClicked
      
    }//GEN-LAST:event_RemoverMouseClicked

    private void calculaTotal() {
        int total = 0;
        
        // Converção para duas casas decimais após a virgula
        DecimalFormat deci = new DecimalFormat("####.##");
        
        ListModel<ProdutosC> modelAtual = ListaSelecionado.getModel();
        for(int c = 0; c<modelAtual.getSize(); c++) {
            total = total+modelAtual.getElementAt(c).preco;
        }
        precoTotal.setText(deci.format(total).replace(',', '.'));
    }
    public void cadastraVenda(){
        VendaClasse v = new VendaClasse();
        v.cliente = Clientes.getSelectedItem().toString();
        v.data = data.getText();
        v.total = Integer.parseInt(precoTotal.getText());
        
        ListModel<ProdutosC> modelAtual = ListaSelecionado.getModel();
        v.produtos = new ArrayList<>();
        for(int c = 0; c<modelAtual.getSize(); c++) {
            v.produtos.add(modelAtual.getElementAt(c));
        }
        
        v.gravaVenda();
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar;
    private javax.swing.JComboBox<Object> Clientes;
    private javax.swing.JButton Finalizar;
    private javax.swing.JList<ProdutosC> ListaProdutos;
    private javax.swing.JList<ProdutosC> ListaSelecionado;
    private javax.swing.JButton Remover;
    private javax.swing.JTextField data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField precoTotal;
    // End of variables declaration//GEN-END:variables
}
